# SPDX-FileCopyrightText: 2025 Koen van Greevenbroek & Aleksander Grochowicz
#
# SPDX-License-Identifier: CC0-1.0

repos:
- repo: https://github.com/ambv/black
  rev: 25.1.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
- repo: https://github.com/timothycrosley/isort
  rev: 6.0.0
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
- repo: https://github.com/econchick/interrogate
  rev: 1.7.0
  hooks:
  - id: interrogate
    args: [-vv, -i, --fail-under=80]
- repo: https://github.com/snakemake/snakefmt
  rev: v0.10.2
  hooks:
  - id: snakefmt
- repo: https://github.com/fsfe/reuse-tool
  rev: v5.0.2
  hooks:
    - id: reuse
